---
title: "Ontology analysis"
output: html_document
params:
  DEG:
    value: DEG
  adjPval:
    value: 0.05
  logFC:
    value: -0.5
---

<!-- Load libraries -->
```{r}
library(dplyr)
```

<!-- Load data --> 
```{r}
DEG         <- params$DEG
logFC       <- as.numeric(params$logFC)
adjPval     <- as.numeric(params$adjPval)
```

```{r}
genes <- readRDS(paste("../data/", DEG, ".rds", sep="")) 
genes
```

```{r}
add_result <- function(genes, logFC, adjPval){
  ifelse(logFC>=0,
      genes <- genes %>% mutate(result = ifelse(log2FoldChange >= logFC & 
                                                  `p-adj` < adjPval, 
                                                "changed", "other")),
      genes <- genes %>% mutate(result = ifelse(log2FoldChange <= logFC & 
                                                  `p-adj` < adjPval, 
                                                "changed", "other")))
  return(genes)
}

genes <- add_result(genes, logFC, adjPval)

genes
```

```{r}
annot <- readRDS("../views/ens2gene.rds") %>%
  dplyr::rename(ENSEMBLTRANS = "ensembl_transcript_id",
         SYMBOL = "mgi_symbol" )
annot
```

```{r}
ensLookup <- annot %>% left_join(genes) %>% filter(!is.na(result))
ensLookup
```

```{r}
selection <- ensLookup %>% filter(result == "changed") %>% 
    dplyr::select("SYMBOL") %>% unique() 
selection <- as.character(selection$SYMBOL)

selection
```

```{r}
present_table <- ensLookup %>% 
    dplyr::select("SYMBOL") %>% unique()  %>% 
    mutate(present = if_else(SYMBOL %in% selection, 1, 0))

present_table
```

```{r}
present <- as.numeric(present_table$present)
names(present) <- as.character(present_table$SYMBOL)

present
```

```{r}
saveRDS(present, paste("../views/present_", as.character(logFC), "_", 
                       as.character(adjPval), ".RDS", sep=""))
```

```{r}

```

