---
title: "Ontology analysis"
output: html_document
params:
  adjPval:
    value: 0.05
  logFC:
    value: -0.5
  ontology:
    value: BP
  algorithm:
    value: classic
  statistic:
    value: fisher
---

<!-- Load libraries -->
```{r}
library(topGO)
library(org.Mm.eg.db)

library(gridExtra)
library(grid)

library(dplyr)
library(tidyr)
```

<!-- Load data --> 
```{r}
logFC       <- as.character(params$logFC)
adjPval     <- as.character(params$adjPval)

ontology  <- params$ontology
algorithm <- params$algorithm
statistic <- params$statistic
```

```{r}
present <- readRDS(paste("../views/present_", 
                         {logFC}, "_", {adjPval}, ".RDS", sep=""))  
present
```

<!-- Load GO annotation -->
```{r}
allGO2genes <- annFUN.org(
  whichOnto = 'BP',
  feasibleGenes = NULL,
  mapping = 'org.Mm.eg.db',
  ID = 'symbol')

allGO2genes
```

<!-- Create gene annotation -->
```{r echo=TRUE}
selection <- function(allScore) {
  return(allScore == 1)
}

GOdata <- new('topGOdata',
  ontology = ontology,
  allGenes = present,
  geneSel = selection,
  annot = annFUN.GO2genes,
  GO2genes = allGO2genes,
  nodeSize = 10)

GOdata
```

<!-- Tests -->
```{r}
resFisherRank   <- runTest(GOdata,   
                            algorithm = algorithm, 
                            statistic = statistic)
```

```{r}
give_data_frame <- function(GOdata, resultFisher){
  resFisherRank <- GenTable(GOdata, classicFisher = resultFisher, orderBy = "classicFisher", topNodes = 10)
  resFisherRank <- resFisherRank[,c("GO.ID", "Term", "classicFisher")]
  colnames(resFisherRank) <- c("GO_ID", "GO_Term", "pvalue")
  data_frame <- as.data.frame.matrix(resFisherRank) 
  data_frame$pvalue <- round(-log10(as.numeric(data_frame$pvalue)), 2) 
  data_frame <- data_frame %>% arrange(desc(pvalue))
  return(data_frame) 
}

df <- give_data_frame(GOdata, resFisherRank)

df
```

```{r}
library(gridExtra)
pdf(paste("../results/go_table_", {logFC}, "_", {adjPval}, ".pdf", sep=""), 
    height=11, width=10) 
colnames(df) = c("GO ID", "GO Term", "-log10(p-val)")
grid.table(df, rows = NULL)
dev.off()
```

```{r}

```


